=== srebrinb/bbSCS/SystemTrayApp/Docs/selectCertResponseSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "SelectCertResponse",
  "type": "object",
  "properties": {
    "Subject": {
      "id": "Subject",
      "type": "string",
      "description":"E=test@test.bg, CN=Test Profesionalen, OU=BULSTAT:1111111111, OU=Professional Certificate - UES, O=TEST AD, S=EGN:1111111111, C=BG"
      
    },
    "SerialNumber": {
      "id": "SerialNumber",
      "type": "string",
      "description":"009BA6E2"
      
    },
    "Issuer": {
      "id": "Issuer",
      "type": "string",
      "description":"....., C=BG"
    },
    "Thumbprint": {
      "id": "Thumbprint",
      "type": "string",
      "description":"3C0DB07FCEECCB9DD3D961D9EA3F560CA1EB2403"
    },
    "DateTimeNotAfter": {
      "id": "DateTimeNotAfter",
      "type": "string",
      "description":"2016-05-12T15:08:58"
      
    },
    "DateTimeNotBefore": {
      "id": "DateTimeNotBefore",
      "type": "string",
      "description":"2016-05-12T15:08:58"
    },
    "Extensions": {
      "id": "Extensions",
      "type": "array",
      "items": 
        {
          "id": "0",
          "type": "object",
          "properties": {
            "Oid": {
              "id": "Oid",
              "type": "string",
              "description":"2.5.29.14"
            },
            "Name": {
              "id": "Name",
              "type": "string",
              "description":"Subject Key Identifier"
            },
            "Value": {
              "id": "Value",
              "type": "string",
              "description":"5E59E373F8A09CA780FCAA1BCE98E28C0A544376"
            },
            "RawValue": {
              "id": "RawValue",
              "type": "string",
              "description":"BBReWeNz+KCcp4D8qhvOmOKMClRDdg=="
            }
          }
        }
      
    },
    "chain": {
      "id": "chain",
      "type": "array",
      "items": 
        {
          "id": "0",
          "type": "string"
        }
    },
    "CertX509": {
      "id": "CertX509",
      "type": "string"
    },
    "Valid": {
      "id": "Valid",
      "type": "boolean"
    },
    "version": {
      "id": "version",
      "type": "string"
    },
    "status": {
      "id": "status",
      "type": "string"
    },
    "reasonCode": {
      "id": "reasonCode",
      "type": "integer"
    }
  }
}

=== srebrinb/bbSCS/SystemTrayApp/Docs/selectCertResponseExample.json
{
  "Subject": "E=test@test.bg, CN=Test Profesionalen, OU=BULSTAT:1111111111, OU=Professional Certificate - UES, O=TEST AD, S=EGN:1111111111, C=BG",
  "SerialNumber": "009BA6E2",
  "Issuer": "....., C=BG",
  "Thumbprint": "3C0DB07FCEECCB9DD3D961D9EA3F560CA1EB2403",
  "DateTimeNotAfter": "2016-05-12T15:08:58",
  "DateTimeNotBefore": "2015-05-13T15:08:58",
  "Extensions": [
    {
      "Oid": "2.5.29.14",
      "Name": "Subject Key Identifier",
      "Value": "5E59E373F8A09CA780FCAA1BCE98E28C0A544376",
      "RawValue": "BBReWeNz+KCcp4D8qhvOmOKMClRDdg=="
    },
    {
      "Oid": "2.5.29.35",
      "Name": "Authority Key Identifier",
      "Value": "30E30A1F1C40D59A28A8D8902D1862806CE23907",
      "RawValue": "MIGPgBQw4wofHEDVm..."
    }
  ],
  "chain": [
    "MIIHoTCCBY...",
    "MIIHoTCCBY...",
    "MIIHoTCCBY..."
  ],
  "CertX509": "MIIHoTCCBYmgAw....",
  "Valid": true,
  "version": "1.0",
  "status": "ok",
  "reasonCode": 200
}
