=== srebrinb/bbSCS/SystemTrayApp/Docs/signResponseSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "properties": {
    "version": {
      "id": "version",
      "type": "string",
      "default": "1.0"
    },
    "signatureAlgorithm": {
      "id": "signatureAlgorithm",
      "type": "string"
    },
    "signatureType": {
      "id": "signatureType",
      "type": "string"
    },
    "signature": {
      "id": "signature",
      "type": "string"
    },
    "signatures": {
      "id": "signatures",
      "type": "array",
      "items": {
		"type": "string"
	  }
    },
    "chain": {
      "id": "chain",
      "type": "array",
      "items": {
		"type": "string"
	  }
    },
    "status": {
      "id": "status",
      "type": "string"
    },
    "reasonCode": {
      "id": "reasonCode",
      "type": "integer"
    },
    "reasonText": {
      "id": "reasonText",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "version",
    "signatureAlgorithm",
    "signatureType",
    "chain",
    "status",
    "reasonCode",
    "reasonText"
  ]
}

=== srebrinb/bbSCS/SystemTrayApp/Docs/signResponseExample.json
{
  "version": "1.0",
  "signatureAlgorithm": "SHA256withRSA",
  "signatureType": "signature",
  "signature": "eHF1oXKD62+KTSUb3GPNMhYumwjtL...EVvvo++k+fzDK41nvK5lAZSkA==",
  "signatures": [
    "eHF1oXKD62+KTSUb3GPNMhYumwjtL...EVvvo++k+fzDK41nvK5lAZSkA==",
    "eHF1oXKD62+KTSUb3GPNMhYumwjtL...EVvvo++k+fzDK41nvK5lAZSkA=="
  ],
  "chain": [
    "MIIGADCCBOigAwIBAgIEBfetjDA...iLniyk0+r5aasoF7TY9n4tpMWmg==",
    "MIIFcDCCBFigAwIBAgIDAdbDMA0...fBVhROQzKoDAk1DPtg1gOADYfLg==",
    "MIIEHjCCAwagAwIBAgIDAdTAMA0...lEtXfFCfv9DA8MeVIUfa2pTH6Tk="
  ],
  "status": "ok",
  "reasonCode": 200,
  "reasonText": "Signature generated"
}
